version: "3.4"
services:
  python3:
    restart: always # OS起動時にコンテナを自動起動
    build: .
    tty: true
    volumes:
      - ./volume/boot:/boot
      - ./volume/opt/jupyter:/opt/python/jupyter
      - ./volume/opt/jupyterlab:/opt/python/jupyterlab
      - ./volume/opt/library:/opt/python/library
    ports:
      - 8888:8888
